source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'sqlite3', group: [:development, :test]
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'paperclip', '~> 4.3'
gem 'pg', group: :production
gem 'rails_12factor', group: :production

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.0'
  gem 'rubocop', require: false
  gem 'factory_girl_rails'
  gem 'formulaic'
  gem 'factory_girl'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
